version: "3.9"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./src/shared/posts:/app/src/shared/posts  # Persist blog posts
      - ./public/images:/app/public/images
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/manthanexperts.com/fullchain.pem:/etc/letsencrypt/live/manthanexperts.com/fullchain.pem:ro
      - /etc/letsencrypt/live/manthanexperts.com/privkey.pem:/etc/letsencrypt/live/manthanexperts.com/privkey.pem:ro
    restart: always
    depends_on:
      - nextjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
